export const microStxToStx = (micro: number) => micro / 1000000;
export const stxToMicroStx = (stx: number) => Math.floor(stx * 1000000);
export const isValidPrincipal = (addr: string) => /^(S[PM])[a-zA-Z0-9]{37,39}$/.test(addr);
export const isMainnetAddress = (addr: string) => addr.startsWith("SP");
export const isTestnetAddress = (addr: string) => addr.startsWith("ST");
export const truncateAddress = (addr: string) => addr.length > 12 ? `${addr.slice(0, 5)}...${addr.slice(-4)}` : addr;
export const formatStxValue = (micro: number) => `${microStxToStx(micro).toFixed(2)} STX`;
export const parseStxValue = (str: string) => stxToMicroStx(parseFloat(str.replace(/[^0-9\.]/g, "")));
export const extractContractName = (fullAddr: string) => fullAddr.includes(".") ? fullAddr.split(".")[1] : null;
export const extractDeployer = (fullAddr: string) => fullAddr.includes(".") ? fullAddr.split(".")[0] : fullAddr;
export const getExplorerAccountUrl = (addr: string, network: string = "mainnet") => `https://explorer.hiro.so/txid/${addr}?chain=${network}`;
export const getExplorerTxUrl = (txid: string, network: string = "mainnet") => `https://explorer.hiro.so/txid/${txid}?chain=${network}`;
export const ensureHexPrefix = (hex: string) => hex.startsWith("0x") ? hex : `0x${hex}`;
export const stripHexPrefix = (hex: string) => hex.startsWith("0x") ? hex.slice(2) : hex;
export const toSnakeCase = (str: string) => str.replace(/[A-Z]/g, letter => `_${letter.toLowerCase()}`).replace(/^_/, "");
export const calculateFeeThreshold = (feeMultiplier: number) => Math.floor(400 * feeMultiplier);
